//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class admininfo
{
    public admininfo()
    {
        this.fileinfo = new HashSet<fileinfo>();
    }

    public int UID { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string jurisdiction { get; set; }

    public virtual ICollection<fileinfo> fileinfo { get; set; }
}

public partial class articleinfo
{
    public articleinfo()
    {
        this.commentinfo = new HashSet<commentinfo>();
    }

    public int ID { get; set; }
    public Nullable<int> classID { get; set; }
    public string wusername { get; set; }
    public string wtitle { get; set; }
    public string wcontent { get; set; }
    public Nullable<System.DateTime> wpostedtime { get; set; }
    public Nullable<int> wpviews { get; set; }
    public Nullable<int> wcommentsnum { get; set; }
    public string wisFile { get; set; }
    public Nullable<int> fID { get; set; }

    public virtual classinfo classinfo { get; set; }
    public virtual ICollection<commentinfo> commentinfo { get; set; }
}

public partial class blogrollinfo
{
    public int ID { get; set; }
    public string url { get; set; }
    public string title { get; set; }
}

public partial class classinfo
{
    public classinfo()
    {
        this.articleinfo = new HashSet<articleinfo>();
    }

    public int ID { get; set; }
    public string classname { get; set; }

    public virtual ICollection<articleinfo> articleinfo { get; set; }
}

public partial class commentinfo
{
    public commentinfo()
    {
        this.replyCommentinfo = new HashSet<replyCommentinfo>();
    }

    public int ID { get; set; }
    public string pusername { get; set; }
    public Nullable<int> puserID { get; set; }
    public Nullable<int> particleID { get; set; }
    public string pcontent { get; set; }
    public Nullable<System.DateTime> ptime { get; set; }
    public string pIP { get; set; }

    public virtual articleinfo articleinfo { get; set; }
    public virtual userinfo userinfo { get; set; }
    public virtual ICollection<replyCommentinfo> replyCommentinfo { get; set; }
}

public partial class fileinfo
{
    public int ID { get; set; }
    public string url { get; set; }
    public string fType { get; set; }
    public string fUsername { get; set; }
    public Nullable<int> fuserID { get; set; }

    public virtual admininfo admininfo { get; set; }
    public virtual userinfo userinfo { get; set; }
}

public partial class replyCommentinfo
{
    public int ID { get; set; }
    public string pusername { get; set; }
    public Nullable<int> puserID { get; set; }
    public Nullable<int> commentinfoID { get; set; }
    public string pcontent { get; set; }
    public Nullable<System.DateTime> ptime { get; set; }
    public string pIP { get; set; }

    public virtual commentinfo commentinfo { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class userinfo
{
    public userinfo()
    {
        this.commentinfo = new HashSet<commentinfo>();
        this.fileinfo = new HashSet<fileinfo>();
    }

    public int UID { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string jurisdiction { get; set; }
    public Nullable<int> exper { get; set; }

    public virtual ICollection<commentinfo> commentinfo { get; set; }
    public virtual ICollection<fileinfo> fileinfo { get; set; }
}
public partial class statisticsinfo
{
public int line { get; set; }
}