//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_fileinfo_admininfo", "admininfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.admininfo), "fileinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.fileinfo), true)]
[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_articleinfo_classinfo", "classinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.classinfo), "articleinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.articleinfo), true)]
[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_commentinfo_articleinfo", "articleinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.articleinfo), "commentinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.commentinfo), true)]
[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_commentinfo_userinfo", "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.userinfo), "commentinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.commentinfo), true)]
[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_fileinfo_userinfo", "userinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.userinfo), "fileinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.fileinfo), true)]
[assembly: EdmRelationshipAttribute("DbMybbsModel", "FK_replyCommentinfo_commentinfo", "commentinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbMybbsModel.commentinfo), "replyCommentinfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbMybbsModel.replyCommentinfo), true)]

#endregion

namespace DbMybbsModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DbMybbsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DbMybbsEntities”部分中的连接字符串初始化新 DbMybbsEntities 对象。
        /// </summary>
        public DbMybbsEntities() : base("name=DbMybbsEntities", "DbMybbsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DbMybbsEntities 对象。
        /// </summary>
        public DbMybbsEntities(string connectionString) : base(connectionString, "DbMybbsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DbMybbsEntities 对象。
        /// </summary>
        public DbMybbsEntities(EntityConnection connection) : base(connection, "DbMybbsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<admininfo> admininfo
        {
            get
            {
                if ((_admininfo == null))
                {
                    _admininfo = base.CreateObjectSet<admininfo>("admininfo");
                }
                return _admininfo;
            }
        }
        private ObjectSet<admininfo> _admininfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<articleinfo> articleinfo
        {
            get
            {
                if ((_articleinfo == null))
                {
                    _articleinfo = base.CreateObjectSet<articleinfo>("articleinfo");
                }
                return _articleinfo;
            }
        }
        private ObjectSet<articleinfo> _articleinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<blogrollinfo> blogrollinfo
        {
            get
            {
                if ((_blogrollinfo == null))
                {
                    _blogrollinfo = base.CreateObjectSet<blogrollinfo>("blogrollinfo");
                }
                return _blogrollinfo;
            }
        }
        private ObjectSet<blogrollinfo> _blogrollinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<classinfo> classinfo
        {
            get
            {
                if ((_classinfo == null))
                {
                    _classinfo = base.CreateObjectSet<classinfo>("classinfo");
                }
                return _classinfo;
            }
        }
        private ObjectSet<classinfo> _classinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<commentinfo> commentinfo
        {
            get
            {
                if ((_commentinfo == null))
                {
                    _commentinfo = base.CreateObjectSet<commentinfo>("commentinfo");
                }
                return _commentinfo;
            }
        }
        private ObjectSet<commentinfo> _commentinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<fileinfo> fileinfo
        {
            get
            {
                if ((_fileinfo == null))
                {
                    _fileinfo = base.CreateObjectSet<fileinfo>("fileinfo");
                }
                return _fileinfo;
            }
        }
        private ObjectSet<fileinfo> _fileinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<userinfo> userinfo
        {
            get
            {
                if ((_userinfo == null))
                {
                    _userinfo = base.CreateObjectSet<userinfo>("userinfo");
                }
                return _userinfo;
            }
        }
        private ObjectSet<userinfo> _userinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<replyCommentinfo> replyCommentinfo
        {
            get
            {
                if ((_replyCommentinfo == null))
                {
                    _replyCommentinfo = base.CreateObjectSet<replyCommentinfo>("replyCommentinfo");
                }
                return _replyCommentinfo;
            }
        }
        private ObjectSet<replyCommentinfo> _replyCommentinfo;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 admininfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToadmininfo(admininfo admininfo)
        {
            base.AddObject("admininfo", admininfo);
        }
    
        /// <summary>
        /// 用于向 articleinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToarticleinfo(articleinfo articleinfo)
        {
            base.AddObject("articleinfo", articleinfo);
        }
    
        /// <summary>
        /// 用于向 blogrollinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToblogrollinfo(blogrollinfo blogrollinfo)
        {
            base.AddObject("blogrollinfo", blogrollinfo);
        }
    
        /// <summary>
        /// 用于向 classinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToclassinfo(classinfo classinfo)
        {
            base.AddObject("classinfo", classinfo);
        }
    
        /// <summary>
        /// 用于向 commentinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocommentinfo(commentinfo commentinfo)
        {
            base.AddObject("commentinfo", commentinfo);
        }
    
        /// <summary>
        /// 用于向 fileinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTofileinfo(fileinfo fileinfo)
        {
            base.AddObject("fileinfo", fileinfo);
        }
    
        /// <summary>
        /// 用于向 sysdiagrams EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// 用于向 userinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouserinfo(userinfo userinfo)
        {
            base.AddObject("userinfo", userinfo);
        }
    
        /// <summary>
        /// 用于向 replyCommentinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToreplyCommentinfo(replyCommentinfo replyCommentinfo)
        {
            base.AddObject("replyCommentinfo", replyCommentinfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="admininfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class admininfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 admininfo 对象。
        /// </summary>
        /// <param name="uID">UID 属性的初始值。</param>
        public static admininfo Createadmininfo(global::System.Int32 uID)
        {
            admininfo admininfo = new admininfo();
            admininfo.UID = uID;
            return admininfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value, "UID");
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.Int32 _UID;
        partial void OnUIDChanging(global::System.Int32 value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String jurisdiction
        {
            get
            {
                return _jurisdiction;
            }
            set
            {
                OnjurisdictionChanging(value);
                ReportPropertyChanging("jurisdiction");
                _jurisdiction = StructuralObject.SetValidValue(value, true, "jurisdiction");
                ReportPropertyChanged("jurisdiction");
                OnjurisdictionChanged();
            }
        }
        private global::System.String _jurisdiction;
        partial void OnjurisdictionChanging(global::System.String value);
        partial void OnjurisdictionChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_fileinfo_admininfo", "fileinfo")]
        public EntityCollection<fileinfo> fileinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fileinfo>("DbMybbsModel.FK_fileinfo_admininfo", "fileinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fileinfo>("DbMybbsModel.FK_fileinfo_admininfo", "fileinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="articleinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class articleinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 articleinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static articleinfo Createarticleinfo(global::System.Int32 id)
        {
            articleinfo articleinfo = new articleinfo();
            articleinfo.ID = id;
            return articleinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> classID
        {
            get
            {
                return _classID;
            }
            set
            {
                OnclassIDChanging(value);
                ReportPropertyChanging("classID");
                _classID = StructuralObject.SetValidValue(value, "classID");
                ReportPropertyChanged("classID");
                OnclassIDChanged();
            }
        }
        private Nullable<global::System.Int32> _classID;
        partial void OnclassIDChanging(Nullable<global::System.Int32> value);
        partial void OnclassIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wusername
        {
            get
            {
                return _wusername;
            }
            set
            {
                OnwusernameChanging(value);
                ReportPropertyChanging("wusername");
                _wusername = StructuralObject.SetValidValue(value, true, "wusername");
                ReportPropertyChanged("wusername");
                OnwusernameChanged();
            }
        }
        private global::System.String _wusername;
        partial void OnwusernameChanging(global::System.String value);
        partial void OnwusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wtitle
        {
            get
            {
                return _wtitle;
            }
            set
            {
                OnwtitleChanging(value);
                ReportPropertyChanging("wtitle");
                _wtitle = StructuralObject.SetValidValue(value, true, "wtitle");
                ReportPropertyChanged("wtitle");
                OnwtitleChanged();
            }
        }
        private global::System.String _wtitle;
        partial void OnwtitleChanging(global::System.String value);
        partial void OnwtitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcontent
        {
            get
            {
                return _wcontent;
            }
            set
            {
                OnwcontentChanging(value);
                ReportPropertyChanging("wcontent");
                _wcontent = StructuralObject.SetValidValue(value, true, "wcontent");
                ReportPropertyChanged("wcontent");
                OnwcontentChanged();
            }
        }
        private global::System.String _wcontent;
        partial void OnwcontentChanging(global::System.String value);
        partial void OnwcontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> wpostedtime
        {
            get
            {
                return _wpostedtime;
            }
            set
            {
                OnwpostedtimeChanging(value);
                ReportPropertyChanging("wpostedtime");
                _wpostedtime = StructuralObject.SetValidValue(value, "wpostedtime");
                ReportPropertyChanged("wpostedtime");
                OnwpostedtimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _wpostedtime;
        partial void OnwpostedtimeChanging(Nullable<global::System.DateTime> value);
        partial void OnwpostedtimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> wpviews
        {
            get
            {
                return _wpviews;
            }
            set
            {
                OnwpviewsChanging(value);
                ReportPropertyChanging("wpviews");
                _wpviews = StructuralObject.SetValidValue(value, "wpviews");
                ReportPropertyChanged("wpviews");
                OnwpviewsChanged();
            }
        }
        private Nullable<global::System.Int32> _wpviews;
        partial void OnwpviewsChanging(Nullable<global::System.Int32> value);
        partial void OnwpviewsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> wcommentsnum
        {
            get
            {
                return _wcommentsnum;
            }
            set
            {
                OnwcommentsnumChanging(value);
                ReportPropertyChanging("wcommentsnum");
                _wcommentsnum = StructuralObject.SetValidValue(value, "wcommentsnum");
                ReportPropertyChanged("wcommentsnum");
                OnwcommentsnumChanged();
            }
        }
        private Nullable<global::System.Int32> _wcommentsnum;
        partial void OnwcommentsnumChanging(Nullable<global::System.Int32> value);
        partial void OnwcommentsnumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wisFile
        {
            get
            {
                return _wisFile;
            }
            set
            {
                OnwisFileChanging(value);
                ReportPropertyChanging("wisFile");
                _wisFile = StructuralObject.SetValidValue(value, true, "wisFile");
                ReportPropertyChanged("wisFile");
                OnwisFileChanged();
            }
        }
        private global::System.String _wisFile;
        partial void OnwisFileChanging(global::System.String value);
        partial void OnwisFileChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fID
        {
            get
            {
                return _fID;
            }
            set
            {
                OnfIDChanging(value);
                ReportPropertyChanging("fID");
                _fID = StructuralObject.SetValidValue(value, "fID");
                ReportPropertyChanged("fID");
                OnfIDChanged();
            }
        }
        private Nullable<global::System.Int32> _fID;
        partial void OnfIDChanging(Nullable<global::System.Int32> value);
        partial void OnfIDChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_articleinfo_classinfo", "classinfo")]
        public classinfo classinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<classinfo>("DbMybbsModel.FK_articleinfo_classinfo", "classinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<classinfo>("DbMybbsModel.FK_articleinfo_classinfo", "classinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<classinfo> classinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<classinfo>("DbMybbsModel.FK_articleinfo_classinfo", "classinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<classinfo>("DbMybbsModel.FK_articleinfo_classinfo", "classinfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_commentinfo_articleinfo", "commentinfo")]
        public EntityCollection<commentinfo> commentinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<commentinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "commentinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<commentinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "commentinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="blogrollinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class blogrollinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 blogrollinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static blogrollinfo Createblogrollinfo(global::System.Int32 id)
        {
            blogrollinfo blogrollinfo = new blogrollinfo();
            blogrollinfo.ID = id;
            return blogrollinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true, "url");
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="classinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class classinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 classinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static classinfo Createclassinfo(global::System.Int32 id)
        {
            classinfo classinfo = new classinfo();
            classinfo.ID = id;
            return classinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String classname
        {
            get
            {
                return _classname;
            }
            set
            {
                OnclassnameChanging(value);
                ReportPropertyChanging("classname");
                _classname = StructuralObject.SetValidValue(value, true, "classname");
                ReportPropertyChanged("classname");
                OnclassnameChanged();
            }
        }
        private global::System.String _classname;
        partial void OnclassnameChanging(global::System.String value);
        partial void OnclassnameChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_articleinfo_classinfo", "articleinfo")]
        public EntityCollection<articleinfo> articleinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<articleinfo>("DbMybbsModel.FK_articleinfo_classinfo", "articleinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<articleinfo>("DbMybbsModel.FK_articleinfo_classinfo", "articleinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="commentinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class commentinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 commentinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static commentinfo Createcommentinfo(global::System.Int32 id)
        {
            commentinfo commentinfo = new commentinfo();
            commentinfo.ID = id;
            return commentinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pusername
        {
            get
            {
                return _pusername;
            }
            set
            {
                OnpusernameChanging(value);
                ReportPropertyChanging("pusername");
                _pusername = StructuralObject.SetValidValue(value, true, "pusername");
                ReportPropertyChanged("pusername");
                OnpusernameChanged();
            }
        }
        private global::System.String _pusername;
        partial void OnpusernameChanging(global::System.String value);
        partial void OnpusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> puserID
        {
            get
            {
                return _puserID;
            }
            set
            {
                OnpuserIDChanging(value);
                ReportPropertyChanging("puserID");
                _puserID = StructuralObject.SetValidValue(value, "puserID");
                ReportPropertyChanged("puserID");
                OnpuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _puserID;
        partial void OnpuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnpuserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> particleID
        {
            get
            {
                return _particleID;
            }
            set
            {
                OnparticleIDChanging(value);
                ReportPropertyChanging("particleID");
                _particleID = StructuralObject.SetValidValue(value, "particleID");
                ReportPropertyChanged("particleID");
                OnparticleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _particleID;
        partial void OnparticleIDChanging(Nullable<global::System.Int32> value);
        partial void OnparticleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pcontent
        {
            get
            {
                return _pcontent;
            }
            set
            {
                OnpcontentChanging(value);
                ReportPropertyChanging("pcontent");
                _pcontent = StructuralObject.SetValidValue(value, true, "pcontent");
                ReportPropertyChanged("pcontent");
                OnpcontentChanged();
            }
        }
        private global::System.String _pcontent;
        partial void OnpcontentChanging(global::System.String value);
        partial void OnpcontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ptime
        {
            get
            {
                return _ptime;
            }
            set
            {
                OnptimeChanging(value);
                ReportPropertyChanging("ptime");
                _ptime = StructuralObject.SetValidValue(value, "ptime");
                ReportPropertyChanged("ptime");
                OnptimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ptime;
        partial void OnptimeChanging(Nullable<global::System.DateTime> value);
        partial void OnptimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pIP
        {
            get
            {
                return _pIP;
            }
            set
            {
                OnpIPChanging(value);
                ReportPropertyChanging("pIP");
                _pIP = StructuralObject.SetValidValue(value, true, "pIP");
                ReportPropertyChanged("pIP");
                OnpIPChanged();
            }
        }
        private global::System.String _pIP;
        partial void OnpIPChanging(global::System.String value);
        partial void OnpIPChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_commentinfo_articleinfo", "articleinfo")]
        public articleinfo articleinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articleinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "articleinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articleinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "articleinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<articleinfo> articleinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<articleinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "articleinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<articleinfo>("DbMybbsModel.FK_commentinfo_articleinfo", "articleinfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_commentinfo_userinfo", "userinfo")]
        public userinfo userinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_commentinfo_userinfo", "userinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_commentinfo_userinfo", "userinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<userinfo> userinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_commentinfo_userinfo", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<userinfo>("DbMybbsModel.FK_commentinfo_userinfo", "userinfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_replyCommentinfo_commentinfo", "replyCommentinfo")]
        public EntityCollection<replyCommentinfo> replyCommentinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<replyCommentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "replyCommentinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<replyCommentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "replyCommentinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="fileinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fileinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 fileinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static fileinfo Createfileinfo(global::System.Int32 id)
        {
            fileinfo fileinfo = new fileinfo();
            fileinfo.ID = id;
            return fileinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true, "url");
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fType
        {
            get
            {
                return _fType;
            }
            set
            {
                OnfTypeChanging(value);
                ReportPropertyChanging("fType");
                _fType = StructuralObject.SetValidValue(value, true, "fType");
                ReportPropertyChanged("fType");
                OnfTypeChanged();
            }
        }
        private global::System.String _fType;
        partial void OnfTypeChanging(global::System.String value);
        partial void OnfTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fUsername
        {
            get
            {
                return _fUsername;
            }
            set
            {
                OnfUsernameChanging(value);
                ReportPropertyChanging("fUsername");
                _fUsername = StructuralObject.SetValidValue(value, true, "fUsername");
                ReportPropertyChanged("fUsername");
                OnfUsernameChanged();
            }
        }
        private global::System.String _fUsername;
        partial void OnfUsernameChanging(global::System.String value);
        partial void OnfUsernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fuserID
        {
            get
            {
                return _fuserID;
            }
            set
            {
                OnfuserIDChanging(value);
                ReportPropertyChanging("fuserID");
                _fuserID = StructuralObject.SetValidValue(value, "fuserID");
                ReportPropertyChanged("fuserID");
                OnfuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _fuserID;
        partial void OnfuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnfuserIDChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_fileinfo_admininfo", "admininfo")]
        public admininfo admininfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<admininfo>("DbMybbsModel.FK_fileinfo_admininfo", "admininfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<admininfo>("DbMybbsModel.FK_fileinfo_admininfo", "admininfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<admininfo> admininfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<admininfo>("DbMybbsModel.FK_fileinfo_admininfo", "admininfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<admininfo>("DbMybbsModel.FK_fileinfo_admininfo", "admininfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_fileinfo_userinfo", "userinfo")]
        public userinfo userinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_fileinfo_userinfo", "userinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_fileinfo_userinfo", "userinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<userinfo> userinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<userinfo>("DbMybbsModel.FK_fileinfo_userinfo", "userinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<userinfo>("DbMybbsModel.FK_fileinfo_userinfo", "userinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="replyCommentinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class replyCommentinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 replyCommentinfo 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="pIP">pIP 属性的初始值。</param>
        public static replyCommentinfo CreatereplyCommentinfo(global::System.Int32 id, global::System.String pIP)
        {
            replyCommentinfo replyCommentinfo = new replyCommentinfo();
            replyCommentinfo.ID = id;
            replyCommentinfo.pIP = pIP;
            return replyCommentinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pusername
        {
            get
            {
                return _pusername;
            }
            set
            {
                OnpusernameChanging(value);
                ReportPropertyChanging("pusername");
                _pusername = StructuralObject.SetValidValue(value, true, "pusername");
                ReportPropertyChanged("pusername");
                OnpusernameChanged();
            }
        }
        private global::System.String _pusername;
        partial void OnpusernameChanging(global::System.String value);
        partial void OnpusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> puserID
        {
            get
            {
                return _puserID;
            }
            set
            {
                OnpuserIDChanging(value);
                ReportPropertyChanging("puserID");
                _puserID = StructuralObject.SetValidValue(value, "puserID");
                ReportPropertyChanged("puserID");
                OnpuserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _puserID;
        partial void OnpuserIDChanging(Nullable<global::System.Int32> value);
        partial void OnpuserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> commentinfoID
        {
            get
            {
                return _commentinfoID;
            }
            set
            {
                OncommentinfoIDChanging(value);
                ReportPropertyChanging("commentinfoID");
                _commentinfoID = StructuralObject.SetValidValue(value, "commentinfoID");
                ReportPropertyChanged("commentinfoID");
                OncommentinfoIDChanged();
            }
        }
        private Nullable<global::System.Int32> _commentinfoID;
        partial void OncommentinfoIDChanging(Nullable<global::System.Int32> value);
        partial void OncommentinfoIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pcontent
        {
            get
            {
                return _pcontent;
            }
            set
            {
                OnpcontentChanging(value);
                ReportPropertyChanging("pcontent");
                _pcontent = StructuralObject.SetValidValue(value, true, "pcontent");
                ReportPropertyChanged("pcontent");
                OnpcontentChanged();
            }
        }
        private global::System.String _pcontent;
        partial void OnpcontentChanging(global::System.String value);
        partial void OnpcontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ptime
        {
            get
            {
                return _ptime;
            }
            set
            {
                OnptimeChanging(value);
                ReportPropertyChanging("ptime");
                _ptime = StructuralObject.SetValidValue(value, "ptime");
                ReportPropertyChanged("ptime");
                OnptimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ptime;
        partial void OnptimeChanging(Nullable<global::System.DateTime> value);
        partial void OnptimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pIP
        {
            get
            {
                return _pIP;
            }
            set
            {
                OnpIPChanging(value);
                ReportPropertyChanging("pIP");
                _pIP = StructuralObject.SetValidValue(value, false, "pIP");
                ReportPropertyChanged("pIP");
                OnpIPChanged();
            }
        }
        private global::System.String _pIP;
        partial void OnpIPChanging(global::System.String value);
        partial void OnpIPChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_replyCommentinfo_commentinfo", "commentinfo")]
        public commentinfo commentinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<commentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "commentinfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<commentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "commentinfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<commentinfo> commentinfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<commentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "commentinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<commentinfo>("DbMybbsModel.FK_replyCommentinfo_commentinfo", "commentinfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 sysdiagrams 对象。
        /// </summary>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="principal_id">principal_id 属性的初始值。</param>
        /// <param name="diagram_id">diagram_id 属性的初始值。</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbMybbsModel", Name="userinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class userinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 userinfo 对象。
        /// </summary>
        /// <param name="uID">UID 属性的初始值。</param>
        public static userinfo Createuserinfo(global::System.Int32 uID)
        {
            userinfo userinfo = new userinfo();
            userinfo.UID = uID;
            return userinfo;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value, "UID");
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.Int32 _UID;
        partial void OnUIDChanging(global::System.Int32 value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String jurisdiction
        {
            get
            {
                return _jurisdiction;
            }
            set
            {
                OnjurisdictionChanging(value);
                ReportPropertyChanging("jurisdiction");
                _jurisdiction = StructuralObject.SetValidValue(value, true, "jurisdiction");
                ReportPropertyChanged("jurisdiction");
                OnjurisdictionChanged();
            }
        }
        private global::System.String _jurisdiction;
        partial void OnjurisdictionChanging(global::System.String value);
        partial void OnjurisdictionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> exper
        {
            get
            {
                return _exper;
            }
            set
            {
                OnexperChanging(value);
                ReportPropertyChanging("exper");
                _exper = StructuralObject.SetValidValue(value, "exper");
                ReportPropertyChanged("exper");
                OnexperChanged();
            }
        }
        private Nullable<global::System.Int32> _exper;
        partial void OnexperChanging(Nullable<global::System.Int32> value);
        partial void OnexperChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_commentinfo_userinfo", "commentinfo")]
        public EntityCollection<commentinfo> commentinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<commentinfo>("DbMybbsModel.FK_commentinfo_userinfo", "commentinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<commentinfo>("DbMybbsModel.FK_commentinfo_userinfo", "commentinfo", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbMybbsModel", "FK_fileinfo_userinfo", "fileinfo")]
        public EntityCollection<fileinfo> fileinfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fileinfo>("DbMybbsModel.FK_fileinfo_userinfo", "fileinfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fileinfo>("DbMybbsModel.FK_fileinfo_userinfo", "fileinfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
